### ISSUE TITLE
so....

### ISSUE THREAD

**Issue by calebcook** [digidem/filehub-config#4]
I have this device but have no clue how to implement the code on the device. Specifically interested in the Auto Copy of SD cards. Would really appreciate guidance on how to actually modify the device. 😜  thanks!

**Comment by dmgeurts** [comment]
Did you read this: https://github.com/digidem/filehub-config/blob/master/README.md ?

Pretty self explanatory when you follow the instructions. Have a go. There are several versions, pick the one which suits you best. They all get 'installed' in the same way.

**Comment by gmaclennan** [comment]
thanks for the follow up @dmgeurts! always great when others help take the pressure off maintainers :)
